name: build_symbol

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
   
    - name: Cache
      id: rust-cache
      uses: actions/cache@v4
      with:
        path: |
           ~/.cargo/bin/resymgen
        key: rust-cache1
          
    - uses: actions/checkout@v5
      with:
        path: 'dq9Functions'
    - uses: actions/checkout@v5
      if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
      with:
        repository: 'UsernameFodder/pmdsky-debug'
        path: 'pmdsky-debug'
    - name: Build
      if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
      working-directory: pmdsky-debug
      run: cargo build --release
    - name: install
      if: ${{ steps.rust-cache.outputs.cache-hit != 'true' }}
      working-directory: pmdsky-debug
      run: cargo install --path .
    - name: Run build
      working-directory: dq9Functions
      run: |
        resymgen gen --sort --output-dir output/battle symbols/arm9_battle.yml
        resymgen gen --sort --output-dir output/field symbols/arm9_field.yml
        resymgen gen --sort --output-dir output/ram symbols/arm9_ram.yml
    - name: zipping
      working-directory: dq9Functions
      run: |
        find output -type f -name "*_jpn*" -exec zip symbol_jpn.zip {} +
        find output -type f -name "*_eur*" -exec zip symbol_eur.zip {} +
        find output -type f -name "*_usa*" -exec zip symbol_usa.zip {} +
    - name: Update latest branch release
      uses: ncipollo/release-action@v1.18.0
      with:
          artifacts: |
            ${{ github.workspace }}/dq9Functions/symbol_jpn.zip
            ${{ github.workspace }}/dq9Functions/symbol_eur.zip
            ${{ github.workspace }}/dq9Functions/symbol_usa.zip
          makeLatest: ${{ github.ref_name == github.event.repository.default_branch }}
          name: symbol - Latest (Build ${{ github.run_number }})
          tag: symbol-latest
          commit: ${{ github.sha }}
          allowUpdates: true
          removeArtifacts: true
          prerelease: ${{ endsWith(github.ref_name, '-preview') }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jpn
        path: ${{ github.workspace }}/dq9Functions/symbol_jpn.zip 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: eur
        path: ${{ github.workspace }}/dq9Functions/symbol_eur.zip
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: usa
        path: ${{ github.workspace }}/dq9Functions/symbol_usa.zip
          
    
